### ISSUE TITLE
#TK27 Back de página de catálogo

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#106]

**Comment by rpgrca** [comment]
Es el listado de productos, listo el listado y traer producto de a uno (aunque no se probó mucho esto).

**Comment by rpgrca** [comment]
Después si quieren que hagamos MuchosProductos y UnProducto y que los PUT sea a UnProducto en lugar de MuchosProductos lo cambio, por ahora anda.
