### ISSUE TITLE
#TK40 back de barra de navegación con agregado de carrito.

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#129]

**Comment by NataliaAlvarezIspc** [comment]
la barra de navegación no tiene back

**Comment by rpgrca** [comment]
La barra no tiene back pero el carrito si, me equivoqué ayer.

**Comment by rpgrca** [comment]
La vuelvo a cerrar, ya tenemos una tarea para el back del carrito.
