### ISSUE TITLE
Crear logo "EnBalde - Heladería"

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#163]
creare logo en formato png

**Comment by claubott** [comment]
los colores pueden cambiar, pero aquí van un par de ideas:
![imagen](https://user-images.githubusercontent.com/37263110/234446902-59671736-8c3a-4ada-8bd0-7494a5c8a5c9.png)
![imagen](https://user-images.githubusercontent.com/37263110/234447091-2b38d030-e71c-47e1-a64a-624194b7ff33.png)

**Comment by NataliaAlvarezIspc** [comment]
Logo creado
