### ISSUE TITLE
Crear Script BD

### ISSUE THREAD

**Issue by AhumadaCeleste** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#24]
Crear Script BD según modelo entidad de relación.

**Comment by AhumadaCeleste** [comment]
https://github.com/NataliaAlvarezIspc/proyecto-ispc-ecommerce/tree/24-crear-script-bd

**Comment by rpgrca** [comment]
Hay que aplicar algunas correcciones que fui mencionando en la discusión #4 así se podría mergear la base de datos a dev.
