### ISSUE TITLE
#US06 Como usuario cliente quiero tener la posibilidad de modificar datos de registración.

### ISSUE THREAD

**Issue by AhumadaCeleste** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#28]
Hipotéticamente el cliente cambia de domicilio, cuenta de mail, o teléfono de contacto por lo que requiere modificar sus datos de registro. 

- [x] #101
- [x] #102
- [x] #103
- [x] #286

**Comment by rpgrca** [comment]
Listo!
