### ISSUE TITLE
#US08 Cliente desea eliminar los datos de la tarjeta habitual de pago u agregar una nueva.

### ISSUE THREAD

**Issue by AhumadaCeleste** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#33]
Cliente registro una tarjeta habitual de pago y desea  eliminarla cambiarla u agregar una nueva.

**Comment by rpgrca** [comment]
La base de datos no tiene campos para recordar estos datos, además habría que mantenerlos en texto plano lo que es siempre un problema de seguridad. Preferiría que no hagamos esta historia de usuario y que Mercado Pago se encargue de recordar la tarjeta en todo caso.

**Comment by NataliaAlvarezIspc** [comment]
Cierro esta US porque no está contemplada en el proyecto
