### ISSUE TITLE
#TK121 Formulario de productos no indica cuáles son los campos obligatorios

### ISSUE THREAD

**Issue by rpgrca** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#369]
El formulario de productos no indica cuáles son los campos obligatorios con un asterisco. No es necesario hacerle el responsive con un mensaje tipo "el nombre es obligatorio" pero al menos debería decir cuáles son los obligatorios.

**Comment by NataliaAlvarezIspc** [comment]
Hecho en FEATURE de validación de formularios
