### ISSUE TITLE
#TK131 El mail no acepta mayúsculas

### ISSUE THREAD

**Issue by rpgrca** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#379]
Si el mail empieza con mayúsculas no se acepta como válido.

![image](https://github.com/NataliaAlvarezIspc/proyecto-ispc-ecommerce/assets/15602473/30f32053-240e-42b1-b9e0-58417d70b9b9)

**Comment by Brian-Almada** [comment]
(arreglado)

**acepta:**
natalia@gmail.com
Natalia@gmail.com
Natalia1@gmail.com
natalia@Gmail.com
natalia@gmail.Com
Natalia@GMAIL.COM
natalia_@gmail.co
natalia-1@gmail.co
natalia-1@gmail-1.co
natalia@11g.com
natalia@1.com
natalia.a@gmail.com
natalia@gmail.c.com
natalia@gmail.1.com
natalia@1g.com
natalia@gmail.c
natalia-@gmail.co
natalia@gmail-.co

**No acepta:**
natalia,a@gmail.com
natalia;a@gmail.com
natalia@gmail,1.com
natalia@gmail;1.com
natalia@gmail;c.com
natalia@gmail,c.com
natalia,@gmail.com
natalia;@gmail.com
natalia@gmail.com.
natalia@gmail.com@
@natalia@gmail.com
aaa@a.com (por la restricción de más de 10 caracteres)
