### ISSUE TITLE
#TK133 Click en catalogo en resolución baja

### ISSUE THREAD

**Issue by rpgrca** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#381]
En una resolución pequeña el producto se muestra demasiado estirado, debería mostrarse casi como se ve en el catálogo (tal vez deshabilitar el click directamente en resoluciones bajas).

![image](https://github.com/NataliaAlvarezIspc/proyecto-ispc-ecommerce/assets/15602473/b3666c29-1e18-4bf4-8792-fce47bfa3470)

**Comment by BraianTroncoso** [comment]
Realizada
