### ISSUE TITLE
#US11 Como usuario cliente, cuando quiero ver la información detallada de un producto puedo hacer clic en su imagen o nombre para acceder a su página individual.

### ISSUE THREAD

**Issue by AhumadaCeleste** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#39]
Como usuario cliente, cuando quiero ver la información detallada de un producto puedo hacer clic en su imagen o nombre para acceder a su página individual.

- [x] #124
- [x] #125
- [x] #126

**Comment by NataliaAlvarezIspc** [comment]
Corrijo US para que haya cronología

**Comment by rpgrca** [comment]
Listo!
