### ISSUE TITLE
Crear modelo de relacional en base al modelo de datos

### ISSUE THREAD

**Issue by rpgrca** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#4]
Crear el modelo de entidad-relación en base al modelo de datos propuesto.

![image](https://user-images.githubusercontent.com/15602473/230618770-a3bfa6d7-79c5-4c96-a22a-2cb4641ea063.png)

**Comment by AhumadaCeleste** [comment]
[Modelo de flujo.pdf](https://github.com/NataliaAlvarezIspc/proyecto-ispc-ecommerce/files/11195322/Modelo.de.flujo.pdf)

**Comment by AhumadaCeleste** [comment]
[Modelo entidad de relacion.pdf](https://github.com/NataliaAlvarezIspc/proyecto-ispc-ecommerce/files/11195328/Modelo.entidad.de.relacion.pdf)

**Comment by rpgrca** [comment]
La tabla de Localidades no se ve completa.

Personalmente me gusta que los nombres estén completos, o sea que el campo "alicuo" sea "alicuota", ahorrarse dos letras en un nombre de campo no va a hacer que el programa funcione más rápido, igual con el con "usiari" o "cotAr"? También hay nombres de tablas en singular y en plural, "localidades" y "entidad", "articulo" y "provincias". Me da igual una u otra pero preferiría que todas estén en plural o en singular, y sin abreviaturas.

**Comment by rpgrca** [comment]
Se sigue sin ver los campos de la tabla Localidades. Y me parece que la tabla Identificadores no es necesaria, no estoy seguro para qué se usaría, para que un usuario del sistema pueda tener varios clientes? No creo que tengamos que hacer algo tan complicado, que se cree dos cuentas.

**Comment by NataliaAlvarezIspc** [comment]
Este es el diagrama relacional. Corrijo nombre

**Comment by AhumadaCeleste** [comment]
[modelo_relacional.pdf](https://github.com/NataliaAlvarezIspc/proyecto-ispc-ecommerce/files/11215114/modelo_relacional.pdf)

**Comment by AhumadaCeleste** [comment]
![image](https://user-images.githubusercontent.com/106411071/231608382-67f7cd68-070e-47aa-98ae-a4c2420a74f9.png)

**Comment by AhumadaCeleste** [comment]
Agrego tabla envió. 
[modelo_relacional.pdf](https://github.com/NataliaAlvarezIspc/proyecto-ispc-ecommerce/files/11225658/modelo_relacional.pdf)

**Comment by AhumadaCeleste** [comment]
Después de debatirlo en grupo, comparto el ultimo modelo construido entre todo 
![heladeria](https://user-images.githubusercontent.com/106411071/232150208-5a26bf1f-3649-4706-8be2-bc464b439258.svg)

**Comment by rpgrca** [comment]
El usuario debería tener un tipo de usuario para saber si es cliente o administrador, debería ser un int.

**Comment by rpgrca** [comment]
Hay que borrar tabla Identificadores, borrar campo identificador de Usuarios.
Hay que borrar campo localidad de Usuarios.

**Comment by rpgrca** [comment]
La alicuota está bien en MovComprobantes? No era por artículo?

**Comment by rpgrca** [comment]
Cantidad tiene que ser int en DetMovComprobante

**Comment by rpgrca** [comment]
Agregar campo cantidad INT a Articulos

**Comment by BraianTroncoso** [comment]
Finalizada con éxito.
