### ISSUE TITLE
#US12 Como usuario cliente, cuando quiero ver los productos que tengo en mi carrito puedo hacer click en el ícono del carrito en la esquina superior derecha de la pantalla.

### ISSUE THREAD

**Issue by AhumadaCeleste** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#40]
Como usuario cliente, cuando quiero ver los productos que tengo en mi carrito puedo hacer click en el ícono del carrito en la esquina superior derecha de la pantalla en la barra de navegación.

- [x] #127
- [x] #128
- [x] #129

**Comment by NataliaAlvarezIspc** [comment]
Corrijo US para respetar cronología

**Comment by rpgrca** [comment]
Listo!
