### ISSUE TITLE
#US14 Como usuario cliente deseo poder modificar o eliminar los productos del carrito antes de finalizar la compra.

### ISSUE THREAD

**Issue by AhumadaCeleste** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#42]
Como usuario cliente deseo poder modificar o eliminar los productos del carrito antes de finalizar la compra. 

- [x] #133
- [x] #134

**Comment by rpgrca** [comment]
Creo que la base de datos que tenemos no soporta sucursales así que no podrían elegir (al menos por lo que entiendo del diagrama).

**Comment by rpgrca** [comment]
Hay que cerrar esta historia de usuario porque no vamos a soportar múltiples sucursales.

**Comment by NataliaAlvarezIspc** [comment]
Modificación para respetar cronología
