### ISSUE TITLE
#US15 Como usuario cliente, cuando quiero realizar el pago de mi carrito de compras puedo hacer clic en el botón "Pagar" para ingresar mis datos de pago y completar la transacción.

### ISSUE THREAD

**Issue by AhumadaCeleste** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#43]
Como usuario cliente, cuando quiero realizar el pago de mi carrito de compras puedo hacer clic en el botón "Pagar" para ingresar mis datos de pago y completar la transacción.

- [x] #135
- [x] #136
- [x] #137

**Comment by NataliaAlvarezIspc** [comment]
Modifico para respetar cronología

**Comment by rpgrca** [comment]
Listo!
