### ISSUE TITLE
#US16 Como usuario cliente deseo poder seleccionar la forma de pago.

### ISSUE THREAD

**Issue by AhumadaCeleste** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#44]
Como usuario cliente deseo poder seleccionar la forma de pago. El usuario podrá seleccionar entre efectivo y Mercado Pago

- [x] #138
- [x] #139
- [x] #140

**Comment by AhumadaCeleste** [comment]
#51

**Comment by AhumadaCeleste** [comment]
No proyectado en esta etapa del proyecto.

**Comment by NataliaAlvarezIspc** [comment]
Modificado para mantener correlatividad

**Comment by rpgrca** [comment]
Listo!
