### ISSUE TITLE
#US17 Como usuario cliente quiero poder seleccionar entre retirar mi pedido en la tienda o solicitar delivery.

### ISSUE THREAD

**Issue by AhumadaCeleste** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#46]
Como usuario cliente quiero poder seleccionar entre retirar mi pedido en la tienda o solicitar delivery.

- [x] #141
- [x] #142
- [x] #143

**Comment by NataliaAlvarezIspc** [comment]
Modificada para mantener correlatividad

**Comment by rpgrca** [comment]
Listo!
