### ISSUE TITLE
#TK159 Carrito con rectangulo vacio

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#467]
No debería aparecer un rectangulo vacio cuando el carrito no tiene nada

![image](https://github.com/NataliaAlvarezIspc/proyecto-ispc-ecommerce/assets/106571110/1d07dc75-e309-4938-a491-53750929f091)

**Comment by rpgrca** [comment]
Arreglado!
