### ISSUE TITLE
#TK166 Borrar texto despues de agregar tipo de articulo

### ISSUE THREAD

**Issue by rpgrca** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#500]
![image](https://github.com/NataliaAlvarezIspc/proyecto-ispc-ecommerce/assets/15602473/d73e2a8a-2897-45d3-adf9-8693f76a44ea)

**Comment by BraianTroncoso** [comment]
Esta tarea la realicé cuando agregé el texto de la creacion del articulo. (Consulté previamente), por ende ya puede cerrarse.
