### ISSUE TITLE
#TK187 Refrescar cantidad al agregar al carrito

### ISSUE THREAD

**Issue by rpgrca** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#548]
No se está refrescando los elementos del catálogo después de agregar un producto al carrito

**Comment by NataliaAlvarezIspc** [comment]
Esto no está hecho  ya? Cuando agrego algo al carrito me descuenta la cantidad en el catálogo.

**Comment by rpgrca** [comment]
Listo!
