### ISSUE TITLE
#TK190 Retornar nombre del envio en venta

### ISSUE THREAD

**Issue by rpgrca** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#555]
Ahora está retornando el id del envío, hay que cambiarlo para que retorne el nombre.

**Comment by NataliaAlvarezIspc** [comment]
![image](https://github.com/NataliaAlvarezIspc/proyecto-ispc-ecommerce/assets/106571110/bda19edd-57ea-4b0e-89c3-4f98b377989c)

Sería esto lo que hay que cambiar??

**Comment by rpgrca** [comment]
Al revés, el servidor te envía a vos una venta con información, en esa información no incluye el nombre del envío.
