### ISSUE TITLE
Crear mapa del sitio

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#61]

**Comment by rpgrca** [comment]
![image](https://user-images.githubusercontent.com/15602473/232355734-f4dfbb7d-4ce4-4ac2-beb4-79b6e7a0dd0e.png)

Por ahora creo que esto alcanza, faltaría el checkout que estaría en MP, compra equivale a todo el carrito.
