### ISSUE TITLE
#TK206 Al presionar el boton pagar aparece un error en consola

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#614]
y no vacia el carrito.

imagen del error:

![image](https://github.com/NataliaAlvarezIspc/proyecto-ispc-ecommerce/assets/106571110/7f4b34df-7158-4d06-92c6-4fd94fdc06f1)

**Comment by BraianTroncoso** [comment]
![a](https://github.com/NataliaAlvarezIspc/proyecto-ispc-ecommerce/assets/95662710/9b82e6b5-8b2a-415c-9a81-894bc1d333fd)
Este es el error que me tira a mi la consola.

**Comment by BraianTroncoso** [comment]
![a](https://github.com/NataliaAlvarezIspc/proyecto-ispc-ecommerce/assets/95662710/8ca65270-bbd5-4446-a7a6-f45695770e12)
Ahora si me lo tira :)))))))))

**Comment by rpgrca** [comment]
Probalo con la parte de enbalde pago metida.

**Comment by rpgrca** [comment]
Sigue pasando con el ultimo dev? Si no se cierra.

**Comment by BraianTroncoso** [comment]
Probado desde dev, no hay bugs. Buenisimo.
