### ISSUE TITLE
#TK207 Al vaciar carrito y querer elegir del catalogo aparece error en consola

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#615]
Este error aparce al vaciar el carrito dos veces y querer elegir nuevamente un producto del catálogo.

![image](https://github.com/NataliaAlvarezIspc/proyecto-ispc-ecommerce/assets/106571110/21fdd905-1ab1-47d5-b14b-832d83314a6f)

**Comment by rpgrca** [comment]
Sigue pasando con el ultimo dev? Si no se cierra.

**Comment by rpgrca** [comment]
Listo!
