### ISSUE TITLE
#US18 Como usuario cliente, una vez que finalice todos los pasos de la compra, quiero ver una notificación confirmando que la misma fue exitosa.

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#70]
Como usuario cliente, una vez que finalice todos los pasos de la compra, quiero ver una notificación confirmando que la misma fue exitosa.

- [x] #144
- [x] #145
- [x] #146

**Comment by rpgrca** [comment]
Listo!
