### ISSUE TITLE
#TK22 Realizar Back en Python de pantalla de recuperación de contraseña

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#80]
- [x] #535
- [x] #536

**Comment by rpgrca** [comment]
Ver https://learndjango.com/tutorials/django-password-reset-tutorial

**Comment by rpgrca** [comment]
https://studygyaan.com/django/django-rest-framework-tutorial-change-password-and-reset-password
