### ISSUE TITLE
#TK62 Completar modelo Venta

### ISSUE THREAD

**Issue by rpgrca** [NataliaAlvarezIspc/proyecto-ispc-ecommerce#90]
El modelo Venta representa la compra y el pago de un carrito llenado por el cliente.

**Comment by BraianTroncoso** [comment]
Esta clase ya la tengo terminada y lista para pushear. ¿Tendria que hacerlo directo? o ¿Como vemos si esta correcta?

**Comment by rpgrca** [comment]
Listo!
